[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solforge = "G45nBxWsUgxZsu9YTEt9QqHEsxtdc495xqnTR5SRwUAC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/prateektripathi/.openclaw/workspace/autonomous-builder-x/deploy-key.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
